create database games;
use games;

create table game (
  id_game smallint auto_increment not null primary key,
  name_game varchar(255) not null unique,
  genre varchar(255) not null,
  id_dev smallint not null,

  foreign key(id_dev) references developer(id_dev)
);

create table developer (
  id_dev smallint auto_increment not null primary key,
  name_dev varchar(255) not null unique
);
create table award (
  id_award smallint auto_increment not null primary key,
  name_award varchar(255) not null,
  year_award varchar(4) not null,
  id_game smallint not null,

  foreign key(id_game) references game(id_game)
);

insert into developer (name_dev) values 
('Ultimate'),
('Dino Dini'),
('Capcom'),
('Park Place Productions'),
('Ancient'),
('Nintendo EAD'),
('DMA Design'),
('Rockstar North'),
('id Software'),
('Bethesda Game Studios'),
('Epic Games'),
('Infinity Ward'),
('BioWare'),
('Valve'),
('From Software'),
('CD Projekt Red'),
('Nintendo EPD'),
('Naughty Dog'),
('Atari Games'),
('Taito'),
('Bitmap Brothers'),
('Sega'),
('Ocean Software'),
('Core Design'),
('Beam Software');

insert into game (name_game, genre, id_dev) values 
('Jetpac','Shooter', 1),
('Knight Lore','Action-adventure', 1),
('Way of the Exploding Fist','Fighting', 25),
('Gauntlet', 'Hack-and-slash', 19),
('Out Run', 'Racing', 22),
('8-bit computers: Operation Wolf','Light gun shooter', 20),
('16-bit computers: Speedball','Sports', 21),
('Consoles: Thunder Blade','Combat flight simulator', 22),
('8-bit computers: The Untouchables','Shooter', 23),
('16-bit computers: Kick Off', 'Sports', 2),
('8-bit computers: Rick Dangerous 2', 'Platformer', 24),
('16-bit computers: Kick Off 2', 'Sports', 2),
('8-bit consoles: Mega Man', 'Action-platformer', 3),
('16-bit consoles: John Madden American Football','Sports (American football)', 4),
('Sonic the Hedgehog', 'Platformer', 5),
('Street Fighter II', 'Fighting', 3),
('Super Mario 64','Platformer', 6),
('Grand Theft Auto III','Action-adventure', 7),
('Grand Theft Auto: Vice City',  'Action-adventure', 8),
('Doom 3   First-person', 'shooter', 9) ,
('Grand Theft Auto: San Andreas', 'Action-adventure', 8),
('The Elder Scrolls IV: Oblivion',   'Action role-playing', 10),
('Gears of War  Third-person', 'shooter', 11),
('Call of Duty 4: Modern Warfare',   'First-person shooter', 12),
('Fallout 3',  'Action role-playing', 10),
('Mass Effect 2', 'Action role-playing', 13),
('Portal 2', 'Puzzle-platformer', 14),
('The Elder Scrolls V: Skyrim',   'Action role-playing', 10),
('Grand Theft Auto V', 'Action-adventure', 8),
('Dark Souls II', 'Action role-playing', 15),
('The Witcher 3: Wild Hunt', 'Action role-playing', 16),
('Dark Souls III', 'Action role-playing', 15),
('The Legend of Zelda: Breath of the Wild',  'Action-adventure', 17),
('Fortnite Battle Royale',   'Battle royale', 11),
('Resident Evil 2',  'Survival horror', 3),
('The Last of Us Part II','Action-adventure', 18),
('Resident Evil Village', 'Survival horror', 3),
('Elden Ring Action', 'role-playing', 15);

insert into award (name_award, year_award, id_game) values
    ('Golden Joystick Awards','1983',1),
    ('Golden Joystick Awards','1984',2),
    ('Golden Joystick Awards','1985',3),
    ('Golden Joystick Awards','1986',4),
    ('Golden Joystick Awards','1987',5),
    ('Golden Joystick Awards','1988',6),
    ('Golden Joystick Awards','1988',7),
    ('Golden Joystick Awards','1988',8),
    ('Golden Joystick Awards','1989',9),
    ('Golden Joystick Awards','1989',10),
    ('Golden Joystick Awards','1990',11),
    ('Golden Joystick Awards','1990',12),
    ('Golden Joystick Awards','1990',13),
    ('Golden Joystick Awards','1990',14),
    ('Golden Joystick Awards','1991',15),
    ('Golden Joystick Awards','1992',16),
    ('Golden Joystick Awards','1996',17),
    ('Golden Joystick Awards','1997',18),
    ('Golden Joystick Awards','2002',19),
    ('Golden Joystick Awards','2003',20),
    ('Golden Joystick Awards','2004',21),
    ('Golden Joystick Awards','2005',22),
    ('Golden Joystick Awards','2006',23),
    ('Golden Joystick Awards','2008',24),
    ('Golden Joystick Awards','2009',25),
    ('Golden Joystick Awards','2010',26),
    ('Golden Joystick Awards','2011',27),
    ('Golden Joystick Awards','2012',28),
    ('Golden Joystick Awards','2013',29),
    ('Golden Joystick Awards','2014',30),
    ('Golden Joystick Awards','2015',31),
    ('Golden Joystick Awards','2016',32),
    ('Golden Joystick Awards','2017',33),
    ('Golden Joystick Awards','2018',34),
    ('Golden Joystick Awards','2019',35),
    ('Golden Joystick Awards','2020',36),
    ('Golden Joystick Awards','2021',37),
    ('Golden Joystick Awards','2022',38);